import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import { StoreProvider } from "./store/provider";
import { LayoutNavar } from "./components/layoutNavbar/layoutNavbar";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <LayoutNavar />

          {children}

          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
