import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";

import "./globals.css";
import { StoreProvider } from "./store/provider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <nav>
            <Link href="/">Home</Link>

            <Link href="/attributes">Attributes</Link>
          </nav>

          {children}

          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
